# Site settings
title: Jay Blog
header-img: img/home-bg.jpg
email: sunnyjiangjie@foxmail.com
description: "A Wonderful Blog by A Packaging Engineer"
baseurl: ""
url: "http://jayjiang.me"
twitter_username: sunnyjiangjie
github_username:  sunnyjiangjie
facebook_username:  sunnyjiangjie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
